[package]
name = "shadebit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.25.2"
clap = "4.5.15"
password-hash = "0.5.0"
simple_crypt = "*"